### PR TITLE
GNOME + Calamares

### PR DESCRIPTION
**Pull request by fufexan**
- update nixpkgs and remove KDE
- move graphical options into separate file
- flake.lock: update RedNix
- remove kde files
- change xfce to gnome
- GTK colors: remove `_breeze`

### CODE REVIEW

**Comment by AkechiShiro** [comment]
Is there any reason why, you'd change to GNOME precisely and not any other WM ? Why not let the user decide, but I'm not sure if it's that easy, there would be the need to provide a configuration for many WM

**Comment by fufexan** [comment]
@unrooted was complaining that KDE is too slow. We still wanted to use Wayland, without using some WM unfamiliar to a majority of users. So we chose GNOME, as it runs decently on relatively new hardware (last 10 years).

Anyone wanting to use something else can either edit these configs or install using Calamares.

**Comment by AkechiShiro** [comment]
Install using Calamares allows you to choose a specific WM ?

**Comment by fufexan** [comment]
Yes.

**Comment by unrooted** [comment]
@AkechiShiro that's a very good question why one would pick specifically Gnome as their DE over anything else

upon very lively discussions with a few current users, who use RednixOS on mainly VMs, as well as @fufexan, the good switch would be to utilize anything using Wayland in order to minimize, if not fully eliminate infamous X11 tearing effects

as of right now there are 2 properly working DEs for NixOS, which can run using Wayland, and those are either KDE or Gnome, and after a few checks on VMs it seems that Gnome is working a bit smoother

you may ask why not to just go with pure WM without DE, the reason is that it would require users to learn most likely totally new WM, at which point they could just go and do changes themselves, instead of leaving them in unfamiliar environment

that's also where Calamares comes into play, as it provides an option to pick your own DE/WM as well makes install process somewhat easier for less experienced users

what is more, approach presented by @fufexan also cleans up the repo significantally and handles configurations in way more elegant way

feel free to ask us any other questions in case those arise, good to see you still being interested in this project's development, it warms my heart

**Review by unrooted — APPROVED** [review]
lgtm

**Pull request merged**
